/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct msg {
	uint8_t Version_CommandType;
	uint8_t Length;
	uint16_t Checksum;
	int8_t Card[128];
};
typedef struct msg msg;


#define RPC_BJ 0x1
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define hello 0
extern  msg * hello_1(msg *, CLIENT *);
extern  msg * hello_1_svc(msg *, struct svc_req *);
#define start 1
extern  msg * start_1(msg *, CLIENT *);
extern  msg * start_1_svc(msg *, struct svc_req *);
#define send 2
extern  msg * send_1(msg *, CLIENT *);
extern  msg * send_1_svc(msg *, struct svc_req *);
#define betdouble 3
extern  msg * betdouble_1(msg *, CLIENT *);
extern  msg * betdouble_1_svc(msg *, struct svc_req *);
#define hit 4
extern  msg * hit_1(msg *, CLIENT *);
extern  msg * hit_1_svc(msg *, struct svc_req *);
#define stand 5
extern  msg * stand_1(msg *, CLIENT *);
extern  msg * stand_1_svc(msg *, struct svc_req *);
#define ack 6
extern  msg * ack_1(msg *, CLIENT *);
extern  msg * ack_1_svc(msg *, struct svc_req *);
extern int rpc_bj_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define hello 0
extern  msg * hello_1();
extern  msg * hello_1_svc();
#define start 1
extern  msg * start_1();
extern  msg * start_1_svc();
#define send 2
extern  msg * send_1();
extern  msg * send_1_svc();
#define betdouble 3
extern  msg * betdouble_1();
extern  msg * betdouble_1_svc();
#define hit 4
extern  msg * hit_1();
extern  msg * hit_1_svc();
#define stand 5
extern  msg * stand_1();
extern  msg * stand_1_svc();
#define ack 6
extern  msg * ack_1();
extern  msg * ack_1_svc();
extern int rpc_bj_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msg (XDR *, msg*);
extern  bool_t xdr_msg (XDR *, msg*);

#else /* K&R C */
extern bool_t xdr_msg ();
extern bool_t xdr_msg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
