/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct msg {
	int cmd;
	int data;
};
typedef struct msg msg;


#define RPC_GUESS 0x1
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define hello 0
extern  msg * hello_1(msg *, CLIENT *);
extern  msg * hello_1_svc(msg *, struct svc_req *);
#define newgame 1
extern  msg * newgame_1(msg *, CLIENT *);
extern  msg * newgame_1_svc(msg *, struct svc_req *);
#define guess 2
extern  msg * guess_1(msg *, CLIENT *);
extern  msg * guess_1_svc(msg *, struct svc_req *);
extern int rpc_guess_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define hello 0
extern  msg * hello_1();
extern  msg * hello_1_svc();
#define newgame 1
extern  msg * newgame_1();
extern  msg * newgame_1_svc();
#define guess 2
extern  msg * guess_1();
extern  msg * guess_1_svc();
extern int rpc_guess_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msg (XDR *, msg*);
extern  bool_t xdr_msg (XDR *, msg*);

#else /* K&R C */
extern bool_t xdr_msg ();
extern bool_t xdr_msg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
