/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

msg *
hello_1(msg *argp, CLIENT *clnt)
{
	static msg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, hello,
		(xdrproc_t) xdr_msg, (caddr_t) argp,
		(xdrproc_t) xdr_msg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

msg *
newgame_1(msg *argp, CLIENT *clnt)
{
	static msg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, newgame,
		(xdrproc_t) xdr_msg, (caddr_t) argp,
		(xdrproc_t) xdr_msg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

msg *
guess_1(msg *argp, CLIENT *clnt)
{
	static msg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, guess,
		(xdrproc_t) xdr_msg, (caddr_t) argp,
		(xdrproc_t) xdr_msg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
