/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _410121021_140401_H_RPCGEN
#define _410121021_140401_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct msg {
	int value;
};
typedef struct msg msg;

#define RPC_PROG 1
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROC 1
extern  msg * proc_1(msg *, CLIENT *);
extern  msg * proc_1_svc(msg *, struct svc_req *);
extern int rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROC 1
extern  msg * proc_1();
extern  msg * proc_1_svc();
extern int rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msg (XDR *, msg*);

#else /* K&R C */
extern bool_t xdr_msg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_410121021_140401_H_RPCGEN */
