/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct msg {
	int value;
};
typedef struct msg msg;

#define RPC_PROG 1
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define square 1
extern  float * square_1(msg *, CLIENT *);
extern  float * square_1_svc(msg *, struct svc_req *);
#define fib 2
extern  msg * fib_1(msg *, CLIENT *);
extern  msg * fib_1_svc(msg *, struct svc_req *);
extern int rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define square 1
extern  float * square_1();
extern  float * square_1_svc();
#define fib 2
extern  msg * fib_1();
extern  msg * fib_1_svc();
extern int rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msg (XDR *, msg*);

#else /* K&R C */
extern bool_t xdr_msg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
